// Declarations for the baked Poke Transporter GB multiboot image (baked_ptgb_mb.c
// is generated by tools/gen_baked_ptgb.py and is gitignored — the homebrew is not
// redistributed). ptgb_mb_image is padded; ptgb_mb_fsize is the logical size.
#ifndef BAKED_PTGB_MB_H
#define BAKED_PTGB_MB_H
#include <stdint.h>
extern const uint8_t ptgb_mb_image[];
extern const uint32_t ptgb_mb_fsize;
#endif
