// Declarations for the baked Gen3-to-GenX multiboot image (baked_gen3_mb.c is
// generated by tools/gen_baked_gen3.py and is gitignored — the homebrew is not
// redistributed). gen3_mb_image is padded; gen3_mb_fsize is the logical size.
#ifndef BAKED_GEN3_MB_H
#define BAKED_GEN3_MB_H
#include <stdint.h>
extern const uint8_t gen3_mb_image[];
extern const uint32_t gen3_mb_fsize;
#endif
