// AUTO-GENERATED by tools/gen_webui_data.py -- do not edit.
const SPECIES_NAMES = [
  "MissingNo.", "Rhydon", "Kangaskhan", "Nidoran♂", "Clefairy", "Spearow", "Voltorb", "Nidoking",
  "Slowbro", "Ivysaur", "Exeggutor", "Lickitung", "Exeggcute", "Grimer", "Gengar", "Nidoran♀",
  "Nidoqueen", "Cubone", "Rhyhorn", "Lapras", "Arcanine", "Mew", "Gyarados", "Shellder",
  "Tentacool", "Gastly", "Scyther", "Staryu", "Blastoise", "Pinsir", "Tangela", "MissingNo.",
  "MissingNo.", "Growlithe", "Onix", "Fearow", "Pidgey", "Slowpoke", "Kadabra", "Graveler",
  "Chansey", "Machoke", "Mr.Mime", "Hitmonlee", "Hitmonchan", "Arbok", "Parasect", "Psyduck",
  "Drowzee", "Golem", "MissingNo.", "Magmar", "MissingNo.", "Electabuzz", "Magneton", "Koffing",
  "MissingNo.", "Mankey", "Seel", "Diglett", "Tauros", "MissingNo.", "MissingNo.", "MissingNo.",
  "Farfetch'd", "Venonat", "Dragonite", "MissingNo.", "MissingNo.", "MissingNo.", "Doduo", "Poliwag",
  "Jynx", "Moltres", "Articuno", "Zapdos", "Ditto", "Meowth", "Krabby", "MissingNo.",
  "MissingNo.", "MissingNo.", "Vulpix", "Ninetales", "Pikachu", "Raichu", "MissingNo.", "MissingNo.",
  "Dratini", "Dragonair", "Kabuto", "Kabutops", "Horsea", "Seadra", "MissingNo.", "MissingNo.",
  "Sandshrew", "Sandslash", "Omanyte", "Omastar", "Jigglypuff", "Wigglytuff", "Eevee", "Flareon",
  "Jolteon", "Vaporeon", "Machop", "Zubat", "Ekans", "Paras", "Poliwhirl", "Poliwrath",
  "Weedle", "Kakuna", "Beedrill", "MissingNo.", "Dodrio", "Primeape", "Dugtrio", "Venomoth",
  "Dewgong", "MissingNo.", "MissingNo.", "Caterpie", "Metapod", "Butterfree", "Machamp", "MissingNo.",
  "Golduck", "Hypno", "Golbat", "Mewtwo", "Snorlax", "Magikarp", "MissingNo.", "MissingNo.",
  "Muk", "MissingNo.", "Kingler", "Cloyster", "MissingNo.", "Electrode", "Clefable", "Weezing",
  "Persian", "Marowak", "MissingNo.", "Haunter", "Abra", "Alakazam", "Pidgeotto", "Pidgeot",
  "Starmie", "Bulbasaur", "Venusaur", "Tentacruel", "MissingNo.", "Goldeen", "Seaking", "MissingNo.",
  "MissingNo.", "MissingNo.", "MissingNo.", "Ponyta", "Rapidash", "Rattata", "Raticate", "Nidorino",
  "Nidorina", "Geodude", "Porygon", "Aerodactyl", "MissingNo.", "Magnemite", "MissingNo.", "MissingNo.",
  "Charmander", "Squirtle", "Charmeleon", "Wartortle", "Charizard", "MissingNo.", "MissingNo.", "MissingNo.",
  "MissingNo.", "Oddish", "Gloom", "Vileplume", "Bellsprout", "Weepinbell", "Victreebel", "MissingNo.",
  "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.",
  "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.",
  "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.",
  "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.",
  "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.",
  "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.",
  "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.",
  "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo."
];

const SPECIES_NAMES_G2 = [
  "?????", "Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard", "Squirtle",
  "Wartortle", "Blastoise", "Caterpie", "Metapod", "Butterfree", "Weedle", "Kakuna", "Beedrill",
  "Pidgey", "Pidgeotto", "Pidgeot", "Rattata", "Raticate", "Spearow", "Fearow", "Ekans",
  "Arbok", "Pikachu", "Raichu", "Sandshrew", "Sandslash", "Nidoran♀", "Nidorina", "Nidoqueen",
  "Nidoran♂", "Nidorino", "Nidoking", "Clefairy", "Clefable", "Vulpix", "Ninetales", "Jigglypuff",
  "Wigglytuff", "Zubat", "Golbat", "Oddish", "Gloom", "Vileplume", "Paras", "Parasect",
  "Venonat", "Venomoth", "Diglett", "Dugtrio", "Meowth", "Persian", "Psyduck", "Golduck",
  "Mankey", "Primeape", "Growlithe", "Arcanine", "Poliwag", "Poliwhirl", "Poliwrath", "Abra",
  "Kadabra", "Alakazam", "Machop", "Machoke", "Machamp", "Bellsprout", "Weepinbell", "Victreebel",
  "Tentacool", "Tentacruel", "Geodude", "Graveler", "Golem", "Ponyta", "Rapidash", "Slowpoke",
  "Slowbro", "Magnemite", "Magneton", "Farfetch'd", "Doduo", "Dodrio", "Seel", "Dewgong",
  "Grimer", "Muk", "Shellder", "Cloyster", "Gastly", "Haunter", "Gengar", "Onix",
  "Drowzee", "Hypno", "Krabby", "Kingler", "Voltorb", "Electrode", "Exeggcute", "Exeggutor",
  "Cubone", "Marowak", "Hitmonlee", "Hitmonchan", "Lickitung", "Koffing", "Weezing", "Rhyhorn",
  "Rhydon", "Chansey", "Tangela", "Kangaskhan", "Horsea", "Seadra", "Goldeen", "Seaking",
  "Staryu", "Starmie", "Mr.Mime", "Scyther", "Jynx", "Electabuzz", "Magmar", "Pinsir",
  "Tauros", "Magikarp", "Gyarados", "Lapras", "Ditto", "Eevee", "Vaporeon", "Jolteon",
  "Flareon", "Porygon", "Omanyte", "Omastar", "Kabuto", "Kabutops", "Aerodactyl", "Snorlax",
  "Articuno", "Zapdos", "Moltres", "Dratini", "Dragonair", "Dragonite", "Mewtwo", "Mew",
  "Chikorita", "Bayleef", "Meganium", "Cyndaquil", "Quilava", "Typhlosion", "Totodile", "Croconaw",
  "Feraligatr", "Sentret", "Furret", "Hoothoot", "Noctowl", "Ledyba", "Ledian", "Spinarak",
  "Ariados", "Crobat", "Chinchou", "Lanturn", "Pichu", "Cleffa", "Igglybuff", "Togepi",
  "Togetic", "Natu", "Xatu", "Mareep", "Flaaffy", "Ampharos", "Bellossom", "Marill",
  "Azumarill", "Sudowoodo", "Politoed", "Hoppip", "Skiploom", "Jumpluff", "Aipom", "Sunkern",
  "Sunflora", "Yanma", "Wooper", "Quagsire", "Espeon", "Umbreon", "Murkrow", "Slowking",
  "Misdreavus", "Unown", "Wobbuffet", "Girafarig", "Pineco", "Forretress", "Dunsparce", "Gligar",
  "Steelix", "Snubbull", "Granbull", "Qwilfish", "Scizor", "Shuckle", "Heracross", "Sneasel",
  "Teddiursa", "Ursaring", "Slugma", "Magcargo", "Swinub", "Piloswine", "Corsola", "Remoraid",
  "Octillery", "Delibird", "Mantine", "Skarmory", "Houndour", "Houndoom", "Kingdra", "Phanpy",
  "Donphan", "Porygon2", "Stantler", "Smeargle", "Tyrogue", "Hitmontop", "Smoochum", "Elekid",
  "Magby", "Miltank", "Blissey", "Raikou", "Entei", "Suicune", "Larvitar", "Pupitar",
  "Tyranitar", "Lugia", "Ho-Oh", "Celebi", "?????", "Egg", "?????", "?????"
];

const MOVE_NAMES = [
  "—", "Pound", "Karate Chop", "Double Slap", "Comet Punch", "Mega Punch", "Pay Day", "Fire Punch",
  "Ice Punch", "Thunder Punch", "Scratch", "Vise Grip", "Guillotine", "Razor Wind", "Swords Dance", "Cut",
  "Gust", "Wing Attack", "Whirlwind", "Fly", "Bind", "Slam", "Vine Whip", "Stomp",
  "Double Kick", "Mega Kick", "Jump Kick", "Rolling Kick", "Sand Attack", "Headbutt", "Horn Attack", "Fury Attack",
  "Horn Drill", "Tackle", "Body Slam", "Wrap", "Take Down", "Thrash", "Double-Edge", "Tail Whip",
  "Poison Sting", "Twineedle", "Pin Missile", "Leer", "Bite", "Growl", "Roar", "Sing",
  "Supersonic", "Sonic Boom", "Disable", "Acid", "Ember", "Flamethrower", "Mist", "Water Gun",
  "Hydro Pump", "Surf", "Ice Beam", "Blizzard", "Psybeam", "Bubble Beam", "Aurora Beam", "Hyper Beam",
  "Peck", "Drill Peck", "Submission", "Low Kick", "Counter", "Seismic Toss", "Strength", "Absorb",
  "Mega Drain", "Leech Seed", "Growth", "Razor Leaf", "Solar Beam", "Poison Powder", "Stun Spore", "Sleep Powder",
  "Petal Dance", "String Shot", "Dragon Rage", "Fire Spin", "Thunder Shock", "Thunderbolt", "Thunder Wave", "Thunder",
  "Rock Throw", "Earthquake", "Fissure", "Dig", "Toxic", "Confusion", "Psychic", "Hypnosis",
  "Meditate", "Agility", "Quick Attack", "Rage", "Teleport", "Night Shade", "Mimic", "Screech",
  "Double Team", "Recover", "Harden", "Minimize", "Smokescreen", "Confuse Ray", "Withdraw", "Defense Curl",
  "Barrier", "Light Screen", "Haze", "Reflect", "Focus Energy", "Bide", "Metronome", "Mirror Move",
  "Self-Destruct", "Egg Bomb", "Lick", "Smog", "Sludge", "Bone Club", "Fire Blast", "Waterfall",
  "Clamp", "Swift", "Skull Bash", "Spike Cannon", "Constrict", "Amnesia", "Kinesis", "Soft-Boiled",
  "High Jump Kick", "Glare", "Dream Eater", "Poison Gas", "Barrage", "Leech Life", "Lovely Kiss", "Sky Attack",
  "Transform", "Bubble", "Dizzy Punch", "Spore", "Flash", "Psywave", "Splash", "Acid Armor",
  "Crabhammer", "Explosion", "Fury Swipes", "Bonemerang", "Rest", "Rock Slide", "Hyper Fang", "Sharpen",
  "Conversion", "Tri Attack", "Super Fang", "Slash", "Substitute", "Struggle"
];

const TYPE_NAMES = [
  "Normal", "Fighting", "Flying", "Poison", "Ground", "Rock", "", "Bug",
  "Ghost", "", "", "", "", "", "", "",
  "", "", "", "", "Fire", "Water", "Grass", "Electric",
  "Psychic", "Ice", "Dragon", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", ""
];

// Expose for the browser (other <script>s) and for Node tests.
if (typeof globalThis !== 'undefined') {
  globalThis.SPECIES_NAMES = SPECIES_NAMES;
  globalThis.SPECIES_NAMES_G2 = SPECIES_NAMES_G2;
  globalThis.MOVE_NAMES = MOVE_NAMES;
  globalThis.TYPE_NAMES = TYPE_NAMES;
}
if (typeof module !== 'undefined') module.exports = { SPECIES_NAMES, SPECIES_NAMES_G2, MOVE_NAMES, TYPE_NAMES };
