#!/usr/bin/env python3
"""
Generate webui/pokedata_gen3_abilities.js: Gen 3 abilities by *internal* species
id (the same id decodeMonG3 reads from the growth substructure).

Gen 3 stores an ability *slot* bit (0/1) per Pokémon; the name comes from the
species' ability pair. Crucially the pairings must be the **Gen 3** ones — many
species' abilities changed in later games (e.g. Gengar was Levitate in Gen 3,
Cursed Body from Gen 7). So we take the pairings from the trade engine's
Gen-3-accurate `useful_data/rse/abilities.bin` (in-game ability IDs, indexed by
internal species id) and only borrow the ability *names* (IDs 1..77, stable
since Gen 3) from PokeAPI.

Kept separate from pokedata_gen3.js (validated by test_gen3.sh).
"""
import csv
import io
import os
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
OUT_JS = os.path.join(REPO_ROOT, "webui", "pokedata_gen3_abilities.js")
ABIL_BIN = os.path.join(REPO_ROOT, "third_party", "PokemonGB_Online_Trades",
                        "useful_data", "rse", "abilities.bin")
CSV_BASE = "https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/"
ENGLISH = 9


def ability_names():
    """ability_id -> English name (Gen 3 abilities are IDs 1..77, unchanged)."""
    with urllib.request.urlopen(CSV_BASE + "ability_names.csv", timeout=60) as resp:
        rows = list(csv.reader(io.StringIO(resp.read().decode("utf-8"))))
    h = rows[0]
    aid, lid, nm = h.index("ability_id"), h.index("local_language_id"), h.index("name")
    return {int(r[aid]): r[nm] for r in rows[1:] if int(r[lid]) == ENGLISH}


def main():
    if not os.path.exists(ABIL_BIN):
        raise SystemExit(f"missing {ABIL_BIN} — run scripts/setup.sh first")
    data = open(ABIL_BIN, "rb").read()          # 2 bytes per internal id: [slot0, slot1]
    names = ability_names()

    n = len(data) // 2
    table = [None] * n
    for i in range(1, n):                        # 0 = no species
        a0, a1 = data[2 * i], data[2 * i + 1]
        if a0 == 0:
            continue
        name0 = names.get(a0, "")
        name1 = names.get(a1, name0)
        table[i] = [name0, name1 or name0]

    def js(v):
        return "null" if v is None else "[%s]" % ",".join('"%s"' % x for x in v)

    body = ",\n  ".join(js(v) for v in table)
    with open(OUT_JS, "w", encoding="utf-8") as fh:
        fh.write("// Gen 3 abilities by INTERNAL species id -> [slot0, slot1] (English).\n")
        fh.write("// Pairings from the engine's Gen-3 abilities.bin (so they're era-correct);\n")
        fh.write("// names from PokeAPI. Generated by tools/gen_gen3_abilities.py — do not edit.\n")
        fh.write("globalThis.ABILITIES_G3 = [\n  %s,\n];\n" % body)
    filled = sum(1 for v in table if v)
    print(f"wrote {OUT_JS} ({filled} species with Gen-3 abilities)")


if __name__ == "__main__":
    main()
