#!/usr/bin/env python3
"""Generate firmware/path-b-standalone/baked_ptgb_mb.c: the Poke Transporter GB
multiboot image as a flash const array, for on-device (standalone) multiboot. The
image is gitignored (not redistributed, like third_party/); this .c is generated
from it and is also gitignored. Run after the .gba has been built/fetched into
third_party/ptgb/ (see tools/build_ptgb.sh)."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
GBA = os.path.join(REPO, "third_party", "ptgb", "poke_transporter_gb_mb.gba")
OUT = os.path.join(REPO, "firmware", "path-b-standalone", "baked_ptgb_mb.c")


def main():
    if not os.path.isfile(GBA):
        print(f"Missing {GBA}. Run tools/build_ptgb.sh (or scripts/setup.sh).",
              file=sys.stderr)
        return 2
    data = bytearray(open(GBA, "rb").read())
    fsize = len(data)
    fsize_aligned = (fsize + 0xF) & ~0xF          # multiboot rounds up to 16
    data = data.ljust(fsize_aligned + 64, b"\0")  # +64 pad so word reads stay in-bounds
    with open(OUT, "w") as f:
        f.write("// AUTO-GENERATED by tools/gen_baked_ptgb.py — do not edit, do not commit.\n")
        f.write("// Poke Transporter GB multiboot image baked into flash for standalone multiboot.\n")
        f.write('#include "baked_ptgb_mb.h"\n\n')
        f.write(f"const uint32_t ptgb_mb_fsize = {fsize_aligned};  // logical (16-aligned) size\n")
        f.write(f"const uint8_t ptgb_mb_image[{len(data)}] = {{\n")
        for i in range(0, len(data), 16):
            f.write("  " + ",".join(str(b) for b in data[i:i+16]) + ",\n")
        f.write("};\n")
    print(f"wrote {OUT} ({len(data)} bytes, fsize={fsize_aligned})")


if __name__ == "__main__":
    raise SystemExit(main())
