#!/usr/bin/env python3
"""Generate firmware/path-b-standalone/baked_gen3_mb.c: the Gen3-to-GenX multiboot
image as a flash const array, for on-device (standalone) multiboot. The image is
gitignored (not redistributed, like third_party/); this .c is generated from it
and is also gitignored. Run after scripts/setup.sh has fetched the .gba."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
GBA = os.path.join(REPO, "third_party", "gen3", "pokemon_gen3_to_genx_mb.gba")
OUT = os.path.join(REPO, "firmware", "path-b-standalone", "baked_gen3_mb.c")


def main():
    if not os.path.isfile(GBA):
        print(f"Missing {GBA}. Run ./scripts/setup.sh first.", file=sys.stderr)
        return 2
    data = bytearray(open(GBA, "rb").read())
    fsize = len(data)
    fsize_aligned = (fsize + 0xF) & ~0xF          # multiboot rounds up to 16
    data = data.ljust(fsize_aligned + 64, b"\0")  # +64 pad so word reads stay in-bounds
    with open(OUT, "w") as f:
        f.write("// AUTO-GENERATED by tools/gen_baked_gen3.py — do not edit, do not commit.\n")
        f.write("// Gen3-to-GenX multiboot image baked into flash for standalone multiboot.\n")
        f.write('#include "baked_gen3_mb.h"\n\n')
        f.write(f"const uint32_t gen3_mb_fsize = {fsize_aligned};  // logical (16-aligned) size\n")
        f.write(f"const uint8_t gen3_mb_image[{len(data)}] = {{\n")
        for i in range(0, len(data), 16):
            f.write("  " + ",".join(str(b) for b in data[i:i+16]) + ",\n")
        f.write("};\n")
    print(f"wrote {OUT} ({len(data)} bytes, fsize={fsize_aligned})")


if __name__ == "__main__":
    raise SystemExit(main())
