#!/usr/bin/env python3
"""Generate embedded, generation-specific PNG sprites for the ESP32 display."""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
from io import BytesIO
from pathlib import Path
import struct
import urllib.request

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "firmware" / "display-esp32" / "src" / "sprite_data.cpp"
CACHE = ROOT / "firmware" / "display-esp32" / ".sprite-cache"
POKEAPI_COMMIT = "c10459b9b0129eaca5c5d9b1cac65336debb1d08"
BASE = ("https://raw.githubusercontent.com/PokeAPI/sprites/" + POKEAPI_COMMIT +
        "/sprites/pokemon/versions/")
SETS = {
    1: ("generation-i/red-blue/gray", 151),
    2: ("generation-ii/crystal", 251),
    3: ("generation-iii/emerald", 386),
}


def fetch(job: tuple[int, str, int]) -> tuple[int, int, int, int, bytes]:
    generation, path, national = job
    cache_file = CACHE / path.replace("/", "_") / f"{national}.png"
    if cache_file.is_file():
        data = cache_file.read_bytes()
    else:
        request = urllib.request.Request(BASE + path + f"/{national}.png",
                                         headers={"User-Agent": "pico-ball-sprite-generator/1"})
        with urllib.request.urlopen(request, timeout=30) as response:
            data = response.read()
        cache_file.parent.mkdir(parents=True, exist_ok=True)
        cache_file.write_bytes(data)
    if data[:8] != b"\x89PNG\r\n\x1a\n" or len(data) < 24:
        raise RuntimeError(f"invalid PNG for Gen {generation} #{national}")
    actual_width, actual_height = struct.unpack(">II", data[16:24])
    if actual_width < 1 or actual_height < 1 or actual_width > 96 or actual_height > 96:
        raise RuntimeError(f"unexpected Gen {generation} #{national} dimensions "
                           f"{actual_width}x{actual_height}")
    # PNGdec 1.1.6 cannot convert 2-bit grayscale (used by Red/Blue) and takes
    # different branches for indexed Crystal PNGs. Normalize every source to
    # one supported 8-bit RGBA representation so all generations share the
    # same tested decoder path.
    image = Image.open(BytesIO(data)).convert("RGBA")
    normalized = BytesIO()
    image.save(normalized, format="PNG", optimize=True, compress_level=9)
    data = normalized.getvalue()
    if data[24] != 8 or data[25] != 6:
        raise RuntimeError(f"could not normalize Gen {generation} #{national} to RGBA")
    return generation, national, actual_width, actual_height, data


def emit_bytes(name: str, values: bytes) -> str:
    rows = [f"static const uint8_t {name}[] = {{"]
    for start in range(0, len(values), 20):
        rows.append("    " + ", ".join(f"0x{x:02X}" for x in values[start:start + 20]) + ",")
    rows.append("};")
    return "\n".join(rows)


def emit_offsets(name: str, values: list[int]) -> str:
    rows = [f"static const uint32_t {name}[] = {{"]
    for start in range(0, len(values), 12):
        rows.append("    " + ", ".join(str(x) for x in values[start:start + 12]) + ",")
    rows.append("};")
    return "\n".join(rows)


def emit_dimensions(name: str, values: list[int]) -> str:
    rows = [f"static const uint8_t {name}[] = {{"]
    for start in range(0, len(values), 20):
        rows.append("    " + ", ".join(str(x) for x in values[start:start + 20]) + ",")
    rows.append("};")
    return "\n".join(rows)


def main() -> None:
    jobs = [(gen, path, national)
            for gen, (path, count) in SETS.items()
            for national in range(1, count + 1)]
    with ThreadPoolExecutor(max_workers=12) as pool:
        downloaded = list(pool.map(fetch, jobs))
    by_key = {(gen, national): data for gen, national, _, _, data in downloaded}
    dimensions = {(gen, national): (width, height)
                  for gen, national, width, height, _ in downloaded}

    blob = bytearray()
    offsets: dict[int, list[int]] = {}
    widths: dict[int, list[int]] = {}
    heights: dict[int, list[int]] = {}
    for gen, (_, count) in SETS.items():
        table = [0]
        widths[gen] = []
        heights[gen] = []
        for national in range(1, count + 1):
            blob.extend(by_key[(gen, national)])
            table.append(len(blob))
            width, height = dimensions[(gen, national)]
            widths[gen].append(width)
            heights[gen].append(height)
        offsets[gen] = table

    content = """// AUTO-GENERATED by tools/gen_display_sprites.py -- do not edit.
// Source: PokeAPI/sprites pinned to the commit documented by the generator.
#include "sprite_data.h"

"""
    content += emit_bytes("SPRITE_BYTES", bytes(blob)) + "\n\n"
    for gen in SETS:
        content += emit_offsets(f"SPRITE_OFFSETS_G{gen}", offsets[gen]) + "\n\n"
        content += emit_dimensions(f"SPRITE_WIDTHS_G{gen}", widths[gen]) + "\n\n"
        content += emit_dimensions(f"SPRITE_HEIGHTS_G{gen}", heights[gen]) + "\n\n"
    content += """bool sprite_asset(int generation, int national, SpriteAsset *out) {
    if (!out) return false;
    const uint32_t *offsets = nullptr;
    const uint8_t *widths = nullptr, *heights = nullptr;
    int count = 0;
    if (generation == 1) { offsets = SPRITE_OFFSETS_G1; widths = SPRITE_WIDTHS_G1; heights = SPRITE_HEIGHTS_G1; count = 151; }
    else if (generation == 2) { offsets = SPRITE_OFFSETS_G2; widths = SPRITE_WIDTHS_G2; heights = SPRITE_HEIGHTS_G2; count = 251; }
    else if (generation == 3) { offsets = SPRITE_OFFSETS_G3; widths = SPRITE_WIDTHS_G3; heights = SPRITE_HEIGHTS_G3; count = 386; }
    if (!offsets || national < 1 || national > count) return false;
    uint32_t start = offsets[national - 1];
    uint32_t end = offsets[national];
    out->data = SPRITE_BYTES + start;
    out->length = end - start;
    out->width = widths[national - 1];
    out->height = heights[national - 1];
    return true;
}
"""
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT} ({len(blob)} PNG bytes, {len(downloaded)} sprites)")


if __name__ == "__main__":
    main()
