#!/usr/bin/env python3
"""
Generate webui/pokedata.js: lookup tables the in-browser decoder needs.

  * SPECIES_NAMES -- indexed by Gen 1 *internal* index (from the engine's
    pokemon_names.txt; that's what the trade data stores).
  * MOVE_NAMES    -- Gen 1 move names, indexed by move id (baked here).
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
ENGINE_DATA = os.path.join(REPO_ROOT, "third_party", "PokemonGB_Online_Trades", "useful_data")
ENGINE_NAMES = os.path.join(ENGINE_DATA, "rby", "pokemon_names.txt")
GEN2_NAMES = os.path.join(ENGINE_DATA, "gsc", "pokemon_names.txt")
OUT = os.path.join(REPO_ROOT, "webui", "pokedata.js")

# Gen 1 move names, id 0 (none) .. 165. Display-only.
MOVE_NAMES = [
    "—", "Pound", "Karate Chop", "Double Slap", "Comet Punch", "Mega Punch",
    "Pay Day", "Fire Punch", "Ice Punch", "Thunder Punch", "Scratch",
    "Vise Grip", "Guillotine", "Razor Wind", "Swords Dance", "Cut", "Gust",
    "Wing Attack", "Whirlwind", "Fly", "Bind", "Slam", "Vine Whip", "Stomp",
    "Double Kick", "Mega Kick", "Jump Kick", "Rolling Kick", "Sand Attack",
    "Headbutt", "Horn Attack", "Fury Attack", "Horn Drill", "Tackle",
    "Body Slam", "Wrap", "Take Down", "Thrash", "Double-Edge", "Tail Whip",
    "Poison Sting", "Twineedle", "Pin Missile", "Leer", "Bite", "Growl",
    "Roar", "Sing", "Supersonic", "Sonic Boom", "Disable", "Acid", "Ember",
    "Flamethrower", "Mist", "Water Gun", "Hydro Pump", "Surf", "Ice Beam",
    "Blizzard", "Psybeam", "Bubble Beam", "Aurora Beam", "Hyper Beam", "Peck",
    "Drill Peck", "Submission", "Low Kick", "Counter", "Seismic Toss", "Strength",
    "Absorb", "Mega Drain", "Leech Seed", "Growth", "Razor Leaf",
    "Solar Beam", "Poison Powder", "Stun Spore", "Sleep Powder", "Petal Dance",
    "String Shot", "Dragon Rage", "Fire Spin", "Thunder Shock", "Thunderbolt",
    "Thunder Wave", "Thunder", "Rock Throw", "Earthquake", "Fissure", "Dig",
    "Toxic", "Confusion", "Psychic", "Hypnosis", "Meditate", "Agility",
    "Quick Attack", "Rage", "Teleport", "Night Shade", "Mimic", "Screech",
    "Double Team", "Recover", "Harden", "Minimize", "Smokescreen",
    "Confuse Ray", "Withdraw", "Defense Curl", "Barrier", "Light Screen",
    "Haze", "Reflect", "Focus Energy", "Bide", "Metronome", "Mirror Move",
    "Self-Destruct", "Egg Bomb", "Lick", "Smog", "Sludge", "Bone Club",
    "Fire Blast", "Waterfall", "Clamp", "Swift", "Skull Bash", "Spike Cannon",
    "Constrict", "Amnesia", "Kinesis", "Soft-Boiled", "High Jump Kick",
    "Glare", "Dream Eater", "Poison Gas", "Barrage", "Leech Life",
    "Lovely Kiss", "Sky Attack", "Transform", "Bubble", "Dizzy Punch", "Spore",
    "Flash", "Psywave", "Splash", "Acid Armor", "Crabhammer", "Explosion",
    "Fury Swipes", "Bonemerang", "Rest", "Rock Slide", "Hyper Fang", "Sharpen",
    "Conversion", "Tri Attack", "Super Fang", "Slash", "Substitute",
    "Struggle",
]


# Gen 1 type ids -> name (sparse; ids up to 26).
TYPE_NAMES = {
    0: "Normal", 1: "Fighting", 2: "Flying", 3: "Poison", 4: "Ground",
    5: "Rock", 7: "Bug", 8: "Ghost", 20: "Fire", 21: "Water", 22: "Grass",
    23: "Electric", 24: "Psychic", 25: "Ice", 26: "Dragon",
}


def _js_array(name, items):
    body = ",\n  ".join(
        ", ".join(_q(x) for x in items[i : i + 8]) for i in range(0, len(items), 8)
    )
    return f"const {name} = [\n  {body}\n];"


def _q(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _load_names(path):
    with open(path, "r", encoding="utf-8") as fh:
        names = [ln.rstrip("\n") for ln in fh]
    while len(names) < 256:
        names.append(f"#{len(names)}")
    return names


def main():
    names = _load_names(ENGINE_NAMES)        # Gen 1 (internal index order)
    names2 = _load_names(GEN2_NAMES)          # Gen 2 (dex order)
    types = [TYPE_NAMES.get(i, "") for i in range(64)]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    footer = (
        "\n// Expose for the browser (other <script>s) and for Node tests.\n"
        "if (typeof globalThis !== 'undefined') {\n"
        "  globalThis.SPECIES_NAMES = SPECIES_NAMES;\n"
        "  globalThis.SPECIES_NAMES_G2 = SPECIES_NAMES_G2;\n"
        "  globalThis.MOVE_NAMES = MOVE_NAMES;\n"
        "  globalThis.TYPE_NAMES = TYPE_NAMES;\n"
        "}\n"
        "if (typeof module !== 'undefined') module.exports = "
        "{ SPECIES_NAMES, SPECIES_NAMES_G2, MOVE_NAMES, TYPE_NAMES };\n"
    )
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// AUTO-GENERATED by tools/gen_webui_data.py -- do not edit.\n")
        fh.write(_js_array("SPECIES_NAMES", names) + "\n\n")
        fh.write(_js_array("SPECIES_NAMES_G2", names2) + "\n\n")
        fh.write(_js_array("MOVE_NAMES", MOVE_NAMES) + "\n\n")
        fh.write(_js_array("TYPE_NAMES", types) + "\n")
        fh.write(footer)
    print(f"Wrote {OUT}  (Gen1 {len(names)} / Gen2 {len(names2)} species, "
          f"{len(MOVE_NAMES)} moves, {sum(1 for t in types if t)} types)")


if __name__ == "__main__":
    main()
