#!/usr/bin/env python3
"""Generate the ESP32 display's compact species-name lookup header."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "firmware" / "display-esp32" / "src" / "species_names.h"


def js_array(path: Path, name: str) -> list:
    text = path.read_text(encoding="utf-8")
    match = re.search(
        rf"(?:const\s+|globalThis\.){re.escape(name)}\s*=\s*(\[.*?\]);",
        text, re.S)
    if not match:
        raise RuntimeError(f"could not find {name} in {path}")
    return json.loads(re.sub(r",\s*([\]}])", r"\1", match.group(1)))


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def emit_table(name: str, values: list[str]) -> str:
    rows = [f"static const char *const {name}[] = {{"]
    for start in range(0, len(values), 8):
        rows.append("    " + ", ".join(c_string(v) for v in values[start:start + 8]) + ",")
    rows.append("};")
    return "\n".join(rows)


def emit_numbers(name: str, values: list[int], ctype: str = "uint16_t") -> str:
    rows = [f"static const {ctype} {name}[] = {{"]
    for start in range(0, len(values), 16):
        rows.append("    " + ", ".join(str(v) for v in values[start:start + 16]) + ",")
    rows.append("};")
    return "\n".join(rows)


def normalized_name(value: str) -> str:
    return re.sub(r"[^a-z0-9]", "", value.lower())


def main() -> None:
    common = ROOT / "webui" / "pokedata.js"
    gen3 = ROOT / "webui" / "pokedata_gen3.js"
    abilities_file = ROOT / "webui" / "pokedata_gen3_abilities.js"
    g1 = js_array(common, "SPECIES_NAMES")
    g2 = js_array(common, "SPECIES_NAMES_G2")
    g3 = js_array(gen3, "SPECIES_NAMES_G3")
    moves12 = js_array(common, "MOVE_NAMES")
    moves3 = js_array(gen3, "MOVE_NAMES_G3")
    items2 = js_array(common, "ITEM_NAMES_G2")
    items3 = js_array(gen3, "ITEM_NAMES_G3")
    types1 = ["/".join(v) for v in js_array(common, "TYPES_G1")]
    types2 = ["/".join(v) for v in js_array(common, "TYPES_G2")]
    types3 = ["/".join(v) for v in js_array(gen3, "TYPES_G3")]
    int_to_nat3 = js_array(gen3, "INTERNAL_TO_NATIONAL_G3")
    gender2 = js_array(common, "GENDER_RATE_G2")
    gender3 = js_array(gen3, "GENDER_RATE_G3")
    abilities = js_array(abilities_file, "ABILITIES_G3")
    ability0 = [(v[0] if v else "") for v in abilities]
    ability1 = [(v[1] if v and len(v) > 1 else (v[0] if v else "")) for v in abilities]
    national_by_name = {normalized_name(name): i for i, name in enumerate(g2[:252])}
    int_to_nat1 = [national_by_name.get(normalized_name(name), 0) for name in g1]
    content = """// AUTO-GENERATED by tools/gen_display_species.py -- do not edit.\n#pragma once\n#include <stdint.h>\n\n"""
    content += emit_table("SPECIES_NAMES_G1", g1) + "\n\n"
    content += emit_table("SPECIES_NAMES_G2", g2) + "\n\n"
    content += emit_table("SPECIES_NAMES_G3", g3) + "\n\n"
    content += emit_table("MOVE_NAMES_G12", moves12) + "\n\n"
    content += emit_table("MOVE_NAMES_G3", moves3) + "\n\n"
    content += emit_table("ITEM_NAMES_G2", items2) + "\n\n"
    content += emit_table("ITEM_NAMES_G3", items3) + "\n\n"
    content += emit_table("TYPE_NAMES_G1", types1) + "\n\n"
    content += emit_table("TYPE_NAMES_G2", types2) + "\n\n"
    content += emit_table("TYPE_NAMES_G3", types3) + "\n\n"
    content += emit_table("ABILITY_NAMES_G3_0", ability0) + "\n\n"
    content += emit_table("ABILITY_NAMES_G3_1", ability1) + "\n\n"
    content += emit_numbers("INTERNAL_TO_NATIONAL_G1", int_to_nat1) + "\n\n"
    content += emit_numbers("INTERNAL_TO_NATIONAL_G3", int_to_nat3) + "\n\n"
    content += emit_numbers("GENDER_RATE_G2", gender2, "int8_t") + "\n\n"
    content += emit_numbers("GENDER_RATE_G3", gender3, "int8_t") + "\n\n"
    content += """static inline const char *species_name(int generation, int species) {
    const char *name = nullptr;
    if (generation == 1 && species >= 0 && species < (int)(sizeof(SPECIES_NAMES_G1) / sizeof(*SPECIES_NAMES_G1)))
        name = SPECIES_NAMES_G1[species];
    else if (generation == 2 && species >= 0 && species < (int)(sizeof(SPECIES_NAMES_G2) / sizeof(*SPECIES_NAMES_G2)))
        name = SPECIES_NAMES_G2[species];
    else if (generation == 3 && species >= 0 && species < (int)(sizeof(SPECIES_NAMES_G3) / sizeof(*SPECIES_NAMES_G3)))
        name = SPECIES_NAMES_G3[species];
    return name && *name ? name : "Unknown";
}

static inline const char *move_name(int generation, int move) {
    const char *name = nullptr;
    if (generation == 3 && move >= 0 && move < (int)(sizeof(MOVE_NAMES_G3) / sizeof(*MOVE_NAMES_G3)))
        name = MOVE_NAMES_G3[move];
    else if (move >= 0 && move < (int)(sizeof(MOVE_NAMES_G12) / sizeof(*MOVE_NAMES_G12)))
        name = MOVE_NAMES_G12[move];
    return name && *name ? name : "Unknown";
}

static inline const char *item_name(int generation, int item) {
    const char *name = nullptr;
    if (generation == 2 && item >= 0 && item < (int)(sizeof(ITEM_NAMES_G2) / sizeof(*ITEM_NAMES_G2)))
        name = ITEM_NAMES_G2[item];
    else if (generation == 3 && item >= 0 && item < (int)(sizeof(ITEM_NAMES_G3) / sizeof(*ITEM_NAMES_G3)))
        name = ITEM_NAMES_G3[item];
    return name && *name ? name : "None";
}

static inline const char *type_name(int generation, int species) {
    const char *name = nullptr;
    if (generation == 1 && species >= 0 && species < (int)(sizeof(TYPE_NAMES_G1) / sizeof(*TYPE_NAMES_G1)))
        name = TYPE_NAMES_G1[species];
    else if (generation == 2 && species >= 0 && species < (int)(sizeof(TYPE_NAMES_G2) / sizeof(*TYPE_NAMES_G2)))
        name = TYPE_NAMES_G2[species];
    else if (generation == 3 && species >= 0 && species < (int)(sizeof(INTERNAL_TO_NATIONAL_G3) / sizeof(*INTERNAL_TO_NATIONAL_G3))) {
        int national = INTERNAL_TO_NATIONAL_G3[species];
        if (national >= 0 && national < (int)(sizeof(TYPE_NAMES_G3) / sizeof(*TYPE_NAMES_G3)))
            name = TYPE_NAMES_G3[national];
    }
    return name && *name ? name : "Unknown";
}

static inline const char *ability_name(int species, int slot) {
    if (species < 0 || species >= (int)(sizeof(ABILITY_NAMES_G3_0) / sizeof(*ABILITY_NAMES_G3_0)))
        return "Unknown";
    const char *name = slot ? ABILITY_NAMES_G3_1[species] : ABILITY_NAMES_G3_0[species];
    return name && *name ? name : "Unknown";
}

static inline int national_species(int generation, int species) {
    if (generation == 1 && species >= 0 && species < (int)(sizeof(INTERNAL_TO_NATIONAL_G1) / sizeof(*INTERNAL_TO_NATIONAL_G1)))
        return INTERNAL_TO_NATIONAL_G1[species];
    if (generation == 2) return species >= 1 && species <= 251 ? species : 0;
    if (generation == 3 && species >= 0 && species < (int)(sizeof(INTERNAL_TO_NATIONAL_G3) / sizeof(*INTERNAL_TO_NATIONAL_G3)))
        return INTERNAL_TO_NATIONAL_G3[species];
    return 0;
}

static inline int gender_rate(int generation, int national) {
    if (generation == 2 && national >= 0 && national < (int)(sizeof(GENDER_RATE_G2) / sizeof(*GENDER_RATE_G2)))
        return GENDER_RATE_G2[national];
    if (generation == 3 && national >= 0 && national < (int)(sizeof(GENDER_RATE_G3) / sizeof(*GENDER_RATE_G3)))
        return GENDER_RATE_G3[national];
    return -1;
}
"""
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
