#!/usr/bin/env python3
"""
Generate firmware/path-b-standalone/baked_party.h (Gen 1) and
baked_party_gen2.h (Gen 2).

The standalone firmware presents a fixed throwaway "partner" party to the
cartridge during the trade sections. Those outgoing bytes are entirely
determined by our side (base.bin), so we precompute them with the proven
PokemonGB_Online_Trades engine and bake them into C headers; the firmware just
replays them while recording the cartridge's bytes.

  Gen 1 (RBY): sections [random=10, party=418, patches=197]
  Gen 2 (GSC): sections [random=10, party=444, patches=197, mail=385]
Section 0 = base_random_section.bin; the rest = create_trading_data(); each byte
passed through prevent_no_input (0xFE -> alternative) like the engine.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(REPO_ROOT, "host"))

from picovault import engine  # noqa: E402

OUT_DIR = os.path.join(REPO_ROOT, "firmware", "path-b-standalone")


class _FakeLink:
    def send_byte(self, b, n): pass
    def receive_byte(self, n=None): return 0


def _emit_array(name, data):
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 12):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i : i + 12]) + ",")
    lines.append("};")
    return "\n".join(lines)


def build_sections(gen):
    with engine.engine_cwd():
        from utilities.gsc_trading_data_utils import GSCUtilsMisc

        trader = engine.build_trader(_FakeLink(), verbose=False, sanity=True, gen=gen)
        engine.prime_capture_session(trader)
        party = engine.load_base_partner(trader)
        lengths = trader.special_sections_len
        data = party.create_trading_data(lengths)

        folder = engine.GEN_FOLDER[gen]
        rand = list(GSCUtilsMisc.read_data(f"useful_data/{folder}/base_random_section.bin"))
        secs = [rand] + [list(data[i]) for i in range(1, len(lengths))]

        no_input, alt = trader.no_input, trader.no_input_alternative
        secs = [[alt if b == no_input else b for b in s] for s in secs]
        for i, s in enumerate(secs):
            assert len(s) == lengths[i], (gen, i, len(s), lengths[i])
        return secs


def write_header(gen, prefix, guard, out_name):
    secs = build_sections(gen)
    n = len(secs)
    lines = [
        f"// AUTO-GENERATED by tools/gen_baked_party.py -- do not edit by hand.",
        f"// Fixed throwaway partner party for Gen {gen} standalone capture.",
        f"#ifndef {guard}", f"#define {guard}", "#include <stdint.h>", "",
        f"#define {prefix.upper()}SECTION_COUNT {n}",
    ]
    for i, s in enumerate(secs):
        lines.append(f"#define {prefix.upper()}SEC{i}_LEN {len(s)}")
    lines.append("")
    for i, s in enumerate(secs):
        lines.append(_emit_array(f"{prefix}section{i}", s))
        lines.append("")
    arr = ", ".join(f"{prefix}section{i}" for i in range(n))
    lens = ", ".join(f"{prefix.upper()}SEC{i}_LEN" for i in range(n))
    lines.append(f"static const uint8_t *const {prefix}sections[{n}] = {{ {arr} }};")
    lines.append(f"static const uint16_t {prefix}section_lens[{n}] = {{ {lens} }};")
    lines.append(f"#endif // {guard}")

    path = os.path.join(OUT_DIR, out_name)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Wrote {path}  (sections: {[len(s) for s in secs]})")


def main():
    write_header(1, "pb_", "BAKED_PARTY_H", "baked_party.h")
    write_header(2, "pb2_", "BAKED_PARTY_GEN2_H", "baked_party_gen2.h")


if __name__ == "__main__":
    main()
